#NOT FOR PRODUCTION!
services:
  medijolt-db:
    image: mongo:latest
    ports:
      - '27017:27017' # Expose MongoDB on the default port
    volumes:
      - medijolt-db:/data/db
volumes:
  medijolt-db: # Persistent volume for MongoDB data
